---
name: Build, push container image

on:
  push:
    branches:
      - main
      - ci-update_img_build # TODO: rm this after testing out things.
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Extract metadata for Docker
        id: metadata
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            # Create 'latest' tag only upon pushing a tag starting with v*.
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/heads/v') }}
            # Use the git tag for the image metadata.
            type=ref,event=tag

      - name: Log in to GHCR
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true # logout at the end of the job

      - name: QEMU
        uses: docker/setup-qemu-action@1f40c72289eff860ee54a304f1438e3cff362e0a # v4.3.0

      - name: Set up Docker to build multi platform images
        uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0

      # Builds the container image.
      # Only pushes the built image to the registry when it's a tag that starts with v.
      # In other words, publish the image when there's some kind of versioned tag.
      - name: Build image; publish when tag is versioned
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          file: Containerfile
          labels: ${{ steps.metadata.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          push: ${{ startsWith(github.ref, 'refs/tags/v') }}
          tags: ${{ steps.metadata.outputs.tags }}
